services:
  app:
    image: pudding/docker-scrape-web-page-to-markdown:20260404.040512
    tty: true
    user: "${UID}:${GID}"
    command: node /app/index.js "/input/__INPUT__"
    environment:
      - CONTAINER_NAME=docker-scrape-web-page-to-markdown-app
      - LOCAL_VOLUMN_PATH=/input/
      - RUN_COMMAND=node /app/index.js
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      - __SOURCE__:/input/
      - __SOURCE__:/output/